name = "PowerModelsStability"
uuid = "f9e4c324-c3b6-4bca-9c3d-419775f0bd17"
authors = ["Haoxiang Yang", "Harsha Nagarajan", "David M Fobes"]
repo = "https://github.com/lanl-ansi/PowerModelsStability.jl.git"
version = "0.2.3"

[deps]
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"

[compat]
InfrastructureModels = "~0.6.0, 0.7"
Ipopt = ">= 0.4"
JSON = "~0.21"
JuMP = "~0.21, 0.22"
Memento = "~1.0, ~1.1, 1"
PowerModelsDistribution = "~0.11.2, ~0.12, ~0.13"
julia = "^1"

[extras]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Ipopt", "PowerModelsDistribution", "Test"]
